/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as PrepareRouteImport } from './routes/prepare'
import { Route as BriefBriefIdRouteImport } from './routes/brief.$briefId'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareRoute = PrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefBriefIdRoute = BriefBriefIdRouteImport.update({
  id: '/brief/$briefId',
  path: '/brief/$briefId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/prepare': typeof PrepareRoute
  '/brief/$briefId': typeof BriefBriefIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/': typeof ContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/prepare': typeof PrepareRoute
  '/brief/$briefId': typeof BriefBriefIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts': typeof ContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/prepare': typeof PrepareRoute
  '/brief/$briefId': typeof BriefBriefIdRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/': typeof ContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/memory'
    | '/prepare'
    | '/brief/$briefId'
    | '/contacts/$contactId'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/memory'
    | '/prepare'
    | '/brief/$briefId'
    | '/contacts/$contactId'
    | '/contacts'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/memory'
    | '/prepare'
    | '/brief/$briefId'
    | '/contacts/$contactId'
    | '/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  MemoryRoute: typeof MemoryRoute
  PrepareRoute: typeof PrepareRoute
  BriefBriefIdRoute: typeof BriefBriefIdRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare': {
      id: '/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof PrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$briefId': {
      id: '/brief/$briefId'
      path: '/brief/$briefId'
      fullPath: '/brief/$briefId'
      preLoaderRoute: typeof BriefBriefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  MemoryRoute: MemoryRoute,
  PrepareRoute: PrepareRoute,
  BriefBriefIdRoute: BriefBriefIdRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
